before_install:
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3
install: "true"
language: erlang
otp_release:
  - 19.0
  - 18.2.1
script:
  - ./rebar3 do xref,eunit,dialyzer,coveralls send
